name: deploy-unifi-controller
concurrency: unifi-controller

on:
  push:
    branches:
      - master
    paths-ignore:
      - "ARM templates"
      - "README.md"

permissions:
  id-token: write
  contents: write

env:
    ENVIRONMENT: prod
    CONTROLLERNAME: unifi-controller
    VNETCIDR: 172.16.0.0/24
    SUBNETCIDR: 172.16.0.0/28
    VMSIZE: Standard_B1ms
    REGION: eastus
    AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file ./Bicep/main.bicep
  
  build-arm-template:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - uses: actions/checkout@v3
      - name: Compiling ARM template
        run: az bicep build --file ./Bicep/main.bicep --outfile './ARM templates/deploy-unifi-controller.json'

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.SSL_NOTIFICATION_EMAIL }}"
          git config --global user.email "${{ secrets.SSL_NOTIFICATION_EMAIL }}"
          git diff --quiet && git diff --staged --quiet || git commit -am "Updated ARM Template during build run #${{ github.run_number }}"
          git push

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob upload --file './ARM templates/deploy-unifi-controller.json' --container-name 'arm-templates' --name deploy-unifi-controller.json --overwrite

  deploy-unifi-controller:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign into Azure Cloud
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
        name: Deploying Unifi Controller to Azure in ${{ env.REGION }}
        with:
          deploymentName: ${{ github.run_number }}
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.REGION }}
          template: ./Bicep/main.bicep
          parameters:
            restrictedSourceIPaddress="${{ secrets.SOURCE_IP_ADDRESS }}"
            controllerUsername="${{ secrets.CONTROLLER_USERNAME }}"
            sshPublicKey="${{ secrets.SSH_PUBLIC_KEY }}"
            sslExpiryNotificationEmail="${{ secrets.SSL_NOTIFICATION_EMAIL }}"
            environmentName="${{ env.ENVIRONMENT }}"
            controllerName="${{ env.CONTROLLERNAME }}"
            location="${{ env.REGION }}"
            controllerVmSize="${{ env.VMSIZE }}"
            vNetAddressSpace="${{ env.VNETCIDR }}"
            subnetAddressSpace="${{ env.SUBNETCIDR }}"